apiVersion: v2
name: gitops-app
description: >
  Spring Boot GitOps demo application - CI/CD pipeline with Jenkins.
type: application
# chartversion
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - spring-boot
  - gitops
  - java
maintainers:
  - name: Tejas
    email: Tejas@gmail.com